import type { Metadata } from "next";
import { Sawarabi_Mincho } from "next/font/google";
import "./globals.css";
import Header from "@/components/core/Header";
import Footer from "@/components/core/Footer";

const sawarabi = Sawarabi_Mincho({ subsets: ["latin-ext"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={
          sawarabi.className +
          "antialiased tracking-wide bg-purpleDark h-screen flex flex-col justify-between container"
        }
      >
        <Header />
        <div className='flex-1'>{children}</div>

        <Footer />
      </body>
    </html>
  );
}
